services:
  web:
    build: .
    ports:
      - ${APP_PORT}:3000
    environment:
      - NODE_ENV=production
      - NEXTAUTH_URL=${NEXTAUTH_URL}
      - NEXTAUTH_SECRET=${NEXTAUTH_SECRET}
      - PINCODE=${PINCODE}
      - DB_URL=${DB_URL}
