version: '3.1'
services:
  mysqldb:
    image: mysql
    container_name: 'mysql'
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: calendardb
    ports:
      - "3307:3306"